version: '1'
volumes:
  data:

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql

  api:
    container_name: api
    hostname: myhostname
    env_file:
      - ../../.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    ports:
      - 3333:3333
