version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_USER=postgres
      - POSTGRES_DB=api-db
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d api-db']
      interval: 1s
      timeout: 5s
      retries: 20

  pgadmin4:
    ports:
      - '5050:80'

    environment:
      - PGADMIN_DEFAULT_EMAIL=rocket@local.fr
      - PGADMIN_DEFAULT_PASSWORD=admin
    container_name: pgadmin4
    image: dpage/pgadmin4
    depends_on:
      db:
        condition: service_healthy

  api:
    container_name: api
    hostname: myhostname
    env_file:
      - ../../.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    build: .
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    restart: always
    ports:
      - 3333:3333
