version: '3.8'
services:
  api:
    container_name: api
    hostname: myhostname
    env_file:
      - ../../.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    build: .
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    restart: always
    ports:
      - 3333:3333
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d api-db']
      interval: 1s
      timeout: 5s
      retries: 20
