# syntax=docker/dockerfile:1
FROM node:18-alpine AS base

WORKDIR /api
RUN npm i -g pnpm
RUN npm i -g nx

FROM base AS dependencies

COPY apps/api/dist/ .
RUN pnpm install

FROM base AS deploy

COPY . .
